name: dbt CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt and adapter
        run: |
          pip install dbt-core
          pip install dbt-athena-community

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          financial_dbt:
            target: dev
            outputs:
              dev:
                type: athena
                region_name: us-east-1
                database: financial_data_lake
                schema: default
                s3_staging_dir: s3://nelson-financial-data-lake-001/
                work_group: primary
          EOF

      - name: Run dbt deps
        working-directory: financial_dbt
        run: dbt deps

      - name: Run dbt models
        working-directory: financial_dbt
        run: dbt run

      - name: Run dbt tests
        working-directory: financial_dbt
        run: dbt test
