name: dbt CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  dbt-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install dbt-core
          pip install dbt-athena

      - name: Run dbt deps
        run: dbt deps
        working-directory: financial_dbt

      - name: Run dbt models
        run: dbt run
        working-directory: financial_dbt

      - name: Run dbt tests
        run: dbt test
        working-directory: financial_dbt